"use client";

import Exposition from "@/components/Exposition/Exposition";
import Curve from "@/components/Layout/Curve";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function ExpositionSection() {
  const router = useRouter();
  const changePath = router.route == "/Interview";
  const [mounted, setMounted] = useState(false);
  console.log(changePath);
  // useEffect((changePath) => {
  //   setTimeout(() => setMounted(false), 1);
  // }),
  //   [changePath];

  useEffect(() => {
    setTimeout(() => setMounted(true), 1000);
  });

  return (
    <>
      <Head>
        <title>Exposition</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/exposition.ico" />
      </Head>
      <Curve backgroundColor="#6E97D0">{mounted ? <Exposition /> : ""}</Curve>
    </>
  );
}
