"use client";

import Conclution from "@/components/Conclusion/Conclusion";
import Curve from "@/components/Layout/Curve";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function ConclutionSection() {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setTimeout(() => setMounted(true), 1000);
  });
  return (
    <>
      <Head>
        <title>Conclution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve backgroundColor="#6E97D0">{mounted ? <Conclution /> : ""}</Curve>
    </>
  );
}
