import Conclution from "@/components/Conclusion/Conclusion";
import Curve from "@/components/Layout/Curve";
import Head from "next/head";

export default function ConclutionSection() {
  return (
    <>
      <Head>
        <title>Conclution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve backgroundColor="#6E97D0">
        <Conclution />
      </Curve>
    </>
  );
}
