import Head from "next/head";
import Curve from "@/components/Layout/Curve";
import Hero from "@/components/Hero/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Projet de fin préformation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve backgroundColor={"#B0AD98"}>
        <Hero />
      </Curve>
    </>
  );
}
